### ISSUE TITLE
Copy ENB over and create backup folder when launcher starts

### ISSUE THREAD

**Issue by TaranRoth** [Wildlander-mod/Launcher#444]
This is to prevent the game launching with no ENB in the event that users rerun Wabbajack or otherwise remove their ENB installation, similar prevention on the part of the backup folder.

**Comment by MattLish** [comment]
Could we instead perhaps store if this action has taken place on a particular install?
I don't want to be in the habit of doing loads of stuff on the startup of the launcher because that will slow down the path to being able to play. A user with a slow machine shouldn't have to wait for multiple files to be checked and copied before being able to play.
